- name: Check for existing secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: ingress-secret
    namespace: openshift-config
    validate_certs: false
  register: current_secret
  until: current_secret is not failed

- name: Update Ingress
  when: current_secret.resources | length | int == 0
  block:
    - name: Create certificate
      ansible.builtin.include_tasks: certs.yaml
      vars:
        prefix: "*.apps"
        type: "ingress"
        secret_namespace: "openshift-config"

    - name: Patch Ingress Controller
      kubernetes.core.k8s:
        definition:
          apiVersion: config.openshift.io/v1
          kind: Ingress
          metadata:
            name: cluster
          spec:
            componentRoutes:
              - hostname: "{{ 'console-openshift-console.apps.' + domain }}"
                name: console
                namespace: openshift-console
                servingCertKeyPairSecret:
                  name: ingress-secret
              - hostname: "{{ 'oauth-openshift.apps.' + domain }}"
                name: oauth-openshift
                namespace: openshift-authentication
                servingCertKeyPairSecret:
                  name: ingress-secret
        validate_certs: false
        state: present
      register: k8s_result
      until: k8s_result is not failed
